nome = input("Digite o seu nome completo: ")
print("Analizando o seu nome...")
Manome = nome.upper()
Minome = nome.lower()
numero = nome.replace(" ","")
Pnumero = nome.split()
print(Pnumero)
print(f"O seu nome maiúsculo é {Manome}")
print(f"O seu nome minúsculo é {Minome}")
print(f"O seu nome ao todo tem: {len(numero)} letras")
print(f"O seu primeiro nome ao todo tem: {len(Pnumero[0])} letras")
